import turtle
turtle.color("red")
w=turtle.Screen()
w.bgcolor("white")
turtle.up()
turtle.goto(0,-50)
turtle.down()
turtle.hideturtle()
turtle.begin_fill()
turtle.left(140)
turtle.forward(180)
# turtle.left(80)
turtle.circle(-100,200)
turtle.left(120)
turtle.circle(-100,200)
turtle.right(1)
turtle.forward(200)
turtle.end_fill()
turtle.up()
turtle.goto(-50,-90)
turtle.down()
turtle.write("heart shape",font=("Arial",21,"normal"))
turtle.done()