import turtle
# def rectangle(color1,color2,i):
#     turtle.color(color1,color2)
#     turtle.begin_fill()
#     for i in range(i):
#         turtle.right(90)
#         turtle.forward(180)
      
#         # turtle.forward(20)
#     turtle.end_fill()
def func():
    def s():
        print("hi")
    turtle.hideturtle()
    turtle.up()
    turtle.goto(-100,-400)
    turtle.down()
    turtle.left(90)
    turtle.forward(650)
    turtle.color("orange")
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(300)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(300)
    turtle.end_fill()
    # turtle.left(90)
    # turtle.forward(100)
    # turtle.left(90)
    # turtle.forward(500)
    # turtle.left(90)
    turtle.color("white")
    turtle.begin_fill()
    turtle.backward(300)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(300)
    turtle.end_fill()
    turtle.color("green")
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(100)
    turtle.end_fill()
    turtle.color("blue")
    turtle.up()
    turtle.goto(72,129)
    turtle.down()
    turtle.circle(24)
    turtle.right(15)
    turtle.up()
    turtle.goto(41,106)
    turtle.down()

    for i in range(24):
        turtle.forward(24)
        turtle.left(15)
        turtle.bk(24)

    # turtle.circle(20)

    # rectangle("green","green")

    turtle.up()
    turtle.goto(100,-100)
    turtle.down()
    turtle.write("Vande Mataram",font=("Arial Black",21,"normal"))
    turtle.done()
    s()
func()
